### ISSUE TITLE
Precompilation error

### ISSUE THREAD

**Issue by rakeshksr** [zygmuntszpak/ImageComponentAnalysis.jl#34]
Hi @zygmuntszpak, Installing ImageComponentAnalysis.jl raises precompilation error, see below
```
Precompiling project...
  ✗ Adapt → AdaptStaticArraysExt
  4 dependencies successfully precompiled in 63 seconds. 66 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
```

### Environment:
```
(jl_SNKDei) pkg> st
Status `C:\Users\rakesh\AppData\Local\Temp\jl_SNKDei\Project.toml`
  [d9b9e9a0] ImageComponentAnalysis v0.2.0
```

### Version information:
```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × AMD Ryzen 7 PRO 5850U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 1 on 16 virtual cores
```

**Comment by rakeshksr** [comment]
It can fixed by https://github.com/tkoolen/PlanarConvexHulls.jl/pull/14
@tkoolen could you merge [pr](https://github.com/tkoolen/PlanarConvexHulls.jl/pull/14)

**Comment by rakeshksr** [comment]
@zygmuntszpak [Polygon.jl](https://github.com/JuliaImages/Polygon.jl) is an active fork of PlanarConvexHulls.jl maintained by JuliaImages, replacing with it solves problem.

**Comment by tduretz** [comment]
Hi. Is it supposed to be fixed by now? I ask this because I also have a similar precompilation error.

**Comment by zygmuntszpak** [comment]
It turns out `Polygon.jl` is still not registered. I actually started to look into implementing the planar convex hull algorithm myself as a standalone in this package so I fully understand it and can maintain it if need be. In the interim, I have removed the `PlanarConvexHulls` dependency and replaced it with `ConvexHulls2d`. Note however that with the alternative package, while the vertices of the convex hull are listed in the some orientation as previously, the first vertex in the list is not necessarily the same. This is due to the two packages using different underlying algorithms. 

I have just merged this update into master and started the process of tagging a new release [here](https://github.com/JuliaRegistries/General/pull/97019). One the process completes you should have no further issues installing the package.

Please let me know if it all works out.

**Comment by tduretz** [comment]
Thanks a lot! 
I have now removed and reinstalled by doing: `add imageComponentAnalysis#master`. This now works.
 
The standard way: `add imageComponentAnalysis` still crashes but likely registration is not yet finalised.

**Comment by zygmuntszpak** [comment]
I'm surprised the standard way doesn't work since the latest version was in fact registered. Thanks for letting me know. I'll look into it.

**Comment by tduretz** [comment]
Just tried it in a clean environment and it works. My previous test was made in a somehow polluted environment. Sorry for this... Everything works!
